BoxLayout:
    orientation:'vertical'

    MDToolbar:
        title: 'Device Information'
        mode: 'center'
        left_action_items: [["menu", lambda x: app.callback()]]
        md_bg_color: .2, .2, .2, 1
        specific_text_color: 1, 1, 1, 1

    MDBottomNavigation:
        panel_color: .2, .2, .2, 1

        MDBottomNavigationItem:
            name: 'screen 1'
            text: 'Python'
            icon: 'language-python'

            MDBoxLayout:
                orientation: "vertical"
                MDLabel:
                    text: 'Python'
                    halign: 'right'
                MDCard:
                    pos_hint: {"center_x": .5, "center_y": .5}
                    MDLabel:
                        text: 'Boot TIme -' + app.boot_time
                        halign: 'center'

        MDBottomNavigationItem:
            name: 'screen 2'
            text: 'C++'
            icon: 'language-cpp'

            MDLabel:
                text: 'I programming of C++'
                halign: 'center'

        MDBottomNavigationItem:
            name: 'screen 3'
            text: 'JS'
            icon: 'language-javascript'

            MDLabel:
                text: 'JS'
                halign: 'center'